name: Notify on Food Order

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Send notification
        run: |
          echo "Order received!" | mail -s "New Food Order" chengmuntong@gmail.com
